Threat int columns in the right way
collective/collective.z3cform.datagridfield pull request #146
Opened 2023-02-14 16:30 UTC by foxtrot-dfm1

2023-02-23 08:38 UTC, petschki requested changes
Could you please rebase this onto master -> tests will be green then.

Also a test which proves your fix would be very cool.

2023-02-23 13:42 UTC, gforcada reviewed
Only looking at the patch I'm rather at a loss to say if it's good or not, as there is no test to check that it fixes something.

Would it be possible to get one?

There are some basic tests on https://github.com/collective/collective.z3cform.datagridfield/blob/master/src/collective/z3cform/datagridfield/browser.rst

2023-02-23 13:42 UTC, gforcada commented on CHANGES.rst
> +- Treat the int columnts in the right way by deserializer.
```suggestion
- Treat the int columns in the right way by deserializer.
```

As I was asked a review, at least I can spot typos 😄

2023-02-24 13:29 UTC, closed without merging

2023-02-24 15:10 UTC, foxtrot-dfm1 commented on src/collective/z3cform/datagridfield/row.py
> +                        value[field_name]
must be field_type