Fixes issue #166
collective/collective.z3cform.datagridfield pull request #168
Opened 2023-06-07 15:14 UTC by rber474

As commented in issue https://github.com/collective/collective.z3cform.datagridfield/issues/166, widgets should be converted using their own converter

2023-06-09 08:20 UTC, erral approved these changes

2023-06-27 09:19 UTC, petschki requested changes
Looks good ... see my comment.
A changenote in `CHANGES.rst` would be great too.

2023-06-27 09:19 UTC, petschki commented on src/collective/z3cform/datagridfield/datagridfield.py
> +    @property
doubled `@property` decorator ... mistake?

2023-06-27 12:46 UTC, rber474 commented
master seems has fix for this bug.

2023-06-27 12:46 UTC, closed without merging